apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
type: Opaque
data:
  GITHUB_TOKEN: Z2hwX0R5RlZVWDRJZkFpeWc4SUpSNjJjRDRtYVBsWlQ2bjRTQU5uWgo=
  BACKEND_SECRET: Z2hwX0R5RlZVWDRJZkFpeWc4SUpSNjJjRDRtYVBsWlQ2bjRTQU5uWgo=
  AUTH_GITHUB_CLIENT_ID: NDg5MjViZWRjMmE3YTQ1OTUzNDUK
  AUTH_GITHUB_CLIENT_SECRET: Y2M2MmFkN2FkYmYwMGI1ZTY5MDUxYzliMzdjZjA3MDFmMjA4MTdjZgo=
